[package]
name = "jito-jsm-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
dotenv = "0.15.0"
jito-restaking-sanitization = { git = "https://github.com/jito-foundation/restaking.git", version = "=0.0.1" }
jito-jsm-core = { git = "https://github.com/jito-foundation/restaking.git", version = "=0.0.1" }
jito-vault-core = { git = "https://github.com/jito-foundation/restaking.git", version = "=0.0.1" }
jito-restaking-core = { git = "https://github.com/jito-foundation/restaking.git", version = "=0.0.1" }
jito-restaking-sdk = { git = "https://github.com/jito-foundation/restaking.git", version = "=0.0.1" }
jito-vault-sdk = { git = "https://github.com/jito-foundation/restaking.git", version = "=0.0.1" }
solana-client = "~1.17"
solana-program = "~1.17"
solana-sdk = "~1.17"
tokio = { version = "1.39.2", features = ["full"] }
serde_json = "1.0.122"
